//Defining relevant constants to be used by our reducer

export const ALLERGIES_RECEIVED = 'ALLERGIES_RECEIVED';
export const MEDICATIONS_RECEIVED = 'MEDICATIONS_RECEIVED';
export const CONDITIONS_RECEIVED = 'CONDITIONS_RECEIVED';
export const FAMILY_HISTORY_RECEIVED = 'FAMILY_HISTORY_RECEIVED';
export const OBSERVATIONS_RECEIVED = 'OBSERVATIONS_RECEIVED';
export const REPORTS_RECEIVED = 'REPORTS_RECEIVED';
export const IMMUNIZATIONS_RECEIVED = 'IMMUNIZATIONS_RECEIVED';
export const PROCEDURES_RECEIVED = 'PROCEDURES_RECEIVED';
export const DEVICES_RECEIVED = 'DEVICES_RECEIVED';
export const DOCUMENTS_RECEIVED = 'DOCUMENTS_RECEIVED';
export const CARE_PLAN_RECEIVED = 'CARE_PLAN_RECEIVED';

